### ISSUE TITLE
Spreadsheet editor feedback

### ISSUE THREAD

**Issue by tbantle22** [dolthub/dolthub-issues#67]
Can fix quickly:
- [x] Left/right arrows keep you within cell while editing
- [x] Default column number 5/6
- [x] For existing table disabled add column button and only show number of existing columns
- [x] Don’t allow uploading empty spreadsheet
- [x] Create table button to table list
- [x] Clear import error when reopening spreadsheet editor
- [x] Skip extra step after uploading table for update (meant for choosing pks)
- [x] Overwrite error: upload should not consist of more than one table
- [x] Can’t copy/paste table from existing spreadsheet
- [x] Use current branch name for branch automatically
- [x] "cannot update columns for update or replace operations" error
- [x] Two links in + dropdown (create table and upload a file)
- [x] Play button next to table name while editing

To look into:
- [x] Default write sql query insert query should match number of columns and types (https://github.com/dolthub/ld/pull/7520)
- [x] Data type validation in spreadsheet (https://github.com/dolthub/ld/pull/7576)
- [x] Keyless tables
- [ ] Support adding column to existing table (https://github.com/dolthub/dolthub-issues/issues/112)
- [ ] Can’t hold down letter
- [ ] Left/right arrow functionality more similar to google sheets (https://github.com/dolthub/dolthub-issues/issues/113)
- [ ] Select entire row to delete row (https://github.com/dolthub/dolthub-issues/issues/114)
- [x] Pressing browser back button should work
- [x] Diff reordered inserts for new table (not addressing now, made issue https://github.com/dolthub/dolthub-issues/issues/77)

**Comment by tbantle22** [comment]
<img width="1210" alt="Screen Shot 2021-09-30 at 1 16 55 PM" src="https://user-images.githubusercontent.com/29443194/135524427-7c836975-38ed-4397-a93f-fd5d91d6b97a.png">

**Comment by tbantle22** [comment]
Made separate issues for outstanding items, which are less of a priority. Closing this as the main work is done
